---
deployment:
  tasks:
    - export DEPLOYPATH=/home/techembr/public_html/
    - /usr/bin/rsync -rlptD --exclude='.git' --exclude='.gitignore' --exclude='.cpanel.yml' --exclude='README-DEPLOY.txt' --exclude='*.zip' ./ $DEPLOYPATH
